backend:
  name: git-gateway
  repo: matthewsouther/osoberry
  branch: main
  api_root: https://api.github.com
  base_url: https://api.netlify.com
publish_mode: simple
media_folder: src/assets/uploads
public_folder: /assets/uploads
site_url: https://osoberry.school
display_url: https://osoberry.school
logo_url: https://osoberry.school/assets/img/osoberry_logo_400.png
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: src
    create: false
    fields:
      - { label: Body, name: body, widget: markdown }
  - name: blogPosts
    label: Blog Posts
    label_singular: Blog Post
    folder: src/blogPosts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Author, name: author, widget: string }
      - label: Publish Date
        name: date
        widget: datetime
        default: "{{now}}"
        date_format: M/D/YYYY
        time_format: "h:mm A"
      - { label: Description, name: description, widget: text }
      - label: Featured Image
        name: featuredImage
        widget: image
        allow_multiple: false
      - { label: Layout, name: layout, widget: hidden, default: blog }
      - { label: Tags, name: tags, widget: hidden, default: blog }
      - label: Permalink
        name: permalink
        widget: hidden
        default: "blog/{{ page.fileSlug }}/index.html"
      - { label: Body, name: body, widget: markdown }
