backend:
  name: git-gateway
  repo: matthewsouther/osoberry
  branch: main
  api_root: https://api.github.com
  base_url: https://api.netlify.com
publish_mode: simple
media_folder: src/assets/uploads
public_folder: assets/uploads
site_url: https://osoberry.school
display_url: https://osoberry.school
logo_url: https://osoberry.school/assets/img/osoberry_logo_400.png
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: src
    create: false
    fields:
      - { label: Body, name: body, widget: markdown }
